export const crimeReports = [
  {
    id: "CR-2024-001",
    title: "Residential Burglary",
    type: "Burglary",
    location: "123 Maple Street, Downtown",
    date: "2024-04-01",
    time: "14:30",
    status: "Open",
    description:
      "Break-in through rear window. Jewelry and electronics stolen.",
    reportingOfficer: "Officer Smith",
    severity: "Medium",
    evidence: ["Fingerprints", "Security footage"],
    witnesses: ["John Doe", "Jane Smith"],
    assignedTo: "Inspector Johnson",
  },
  {
    id: "CR-2024-002",
    title: "Vehicle Theft",
    type: "Theft",
    location: "456 Oak Avenue, Westside",
    date: "2024-04-02",
    time: "22:15",
    status: "In Progress",
    description: "Blue Honda Civic stolen from shopping mall parking lot.",
    reportingOfficer: "Officer Wilson",
    severity: "Medium",
    evidence: ["Security footage", "Witness statements"],
    witnesses: ["Michael Brown", "Sarah Wilson"],
    assignedTo: "Sergeant Adams",
  },
  {
    id: "CR-2024-003",
    title: "Assault at Nightclub",
    type: "Assault",
    location: "789 Club Street, Downtown",
    date: "2024-04-03",
    time: "01:45",
    status: "Open",
    description:
      "Physical altercation between two patrons resulting in injuries.",
    reportingOfficer: "Officer Johnson",
    severity: "High",
    evidence: ["Security footage", "Weapons collected", "Medical reports"],
    witnesses: ["Club security", "Multiple patrons"],
    assignedTo: "Inspector Johnson",
  },
  {
    id: "CR-2024-004",
    title: "Shoplifting Incident",
    type: "Theft",
    location: "Main Street Mall",
    date: "2024-04-03",
    time: "15:20",
    status: "Closed",
    description: "Suspect apprehended with stolen clothing items worth $350.",
    reportingOfficer: "Officer Clark",
    severity: "Low",
    evidence: ["Security footage", "Stolen merchandise"],
    witnesses: ["Store clerk", "Security guard"],
    assignedTo: "Officer Smith",
  },
  {
    id: "CR-2024-005",
    title: "Vandalism at Public Park",
    type: "Vandalism",
    location: "Central Park, East Side",
    date: "2024-04-04",
    time: "23:10",
    status: "Open",
    description:
      "Graffiti on public property and damaged playground equipment.",
    reportingOfficer: "Officer Martinez",
    severity: "Low",
    evidence: ["Photographs", "Spray paint cans"],
    witnesses: ["Park security"],
    assignedTo: "Officer Wilson",
  },
  {
    id: "CR-2024-006",
    title: "Armed Robbery",
    type: "Robbery",
    location: "First National Bank, Main Street",
    date: "2024-04-05",
    time: "10:30",
    status: "In Progress",
    description:
      "Two armed suspects took approximately $50,000 and fled in a black SUV.",
    reportingOfficer: "Officer Rodriguez",
    severity: "High",
    evidence: ["Security footage", "Weapon", "Witness statements"],
    witnesses: ["Bank teller", "Multiple customers"],
    assignedTo: "Detective Thompson",
  },
  {
    id: "CR-2024-007",
    title: "Drug Possession",
    type: "Narcotics",
    location: "Green Street, North District",
    date: "2024-04-05",
    time: "22:45",
    status: "In Progress",
    description:
      "Suspect found with illicit substances during routine traffic stop.",
    reportingOfficer: "Officer Brown",
    severity: "Medium",
    evidence: ["Drug samples", "Vehicle search results"],
    witnesses: ["Arresting officer"],
    assignedTo: "Narcotics Division",
  },
  {
    id: "CR-2024-008",
    title: "Identity Theft",
    type: "Fraud",
    location: "Online/Various Locations",
    date: "2024-04-06",
    time: "N/A",
    status: "Open",
    description:
      "Victim reports unauthorized credit card transactions and new accounts opened.",
    reportingOfficer: "Officer Davis",
    severity: "Medium",
    evidence: ["Financial records", "Email communications"],
    witnesses: ["Victim"],
    assignedTo: "Cyber Crimes Unit",
  },
  {
    id: "CR-2024-009",
    title: "Missing Person",
    type: "Missing Person",
    location: "Last seen at River Plaza",
    date: "2024-04-07",
    time: "19:30",
    status: "Critical",
    description: "16-year-old female missing since yesterday evening.",
    reportingOfficer: "Officer Garcia",
    severity: "High",
    evidence: ["Photographs", "Phone records"],
    witnesses: ["Family members", "Friends"],
    assignedTo: "Detective Anderson",
  },
  {
    id: "CR-2024-010",
    title: "Domestic Dispute",
    type: "Domestic Violence",
    location: "567 Pine Road, Suburb",
    date: "2024-04-08",
    time: "21:15",
    status: "Resolved",
    description:
      "Verbal altercation between spouses, no physical harm reported.",
    reportingOfficer: "Officer Wilson",
    severity: "Medium",
    evidence: ["Audio recording", "Statements"],
    witnesses: ["Neighbor"],
    assignedTo: "Family Services Unit",
  },
  {
    id: "CR-2024-011",
    title: "Commercial Burglary",
    type: "Burglary",
    location: "Tech Store, Shopping Center",
    date: "2024-04-09",
    time: "03:20",
    status: "Open",
    description: "Forced entry through back door, multiple devices stolen.",
    reportingOfficer: "Officer Thompson",
    severity: "Medium",
    evidence: ["Security footage", "Tool marks", "Fingerprints"],
    witnesses: ["Security guard"],
    assignedTo: "Sergeant Davis",
  },
  {
    id: "CR-2024-012",
    title: "Hit and Run",
    type: "Traffic Incident",
    location: "Highway 101, Mile Marker 23",
    date: "2024-04-10",
    time: "17:45",
    status: "Open",
    description:
      "Victim's vehicle struck by unknown driver who fled the scene.",
    reportingOfficer: "Officer Roberts",
    severity: "High",
    evidence: ["Vehicle damage photos", "Traffic camera footage"],
    witnesses: ["Multiple drivers"],
    assignedTo: "Traffic Division",
  },
];

export const caseManagement = [
  {
    id: "CM-2024-001",
    crimeReportId: "CR-2024-001",
    title: "Residential Burglary Investigation",
    status: "Active",
    priority: "Medium",
    dateOpened: "2024-04-01",
    description: "Investigation into residential burglary at 123 Maple Street.",
    assignedTo: "Inspector Johnson",
    lastUpdated: "2024-04-03",
    progress: 25,
    notes: [
      {
        id: "N1",
        date: "2024-04-01",
        author: "Officer Smith",
        content:
          "Initial evidence collected from the scene. Multiple fingerprints identified.",
      },
      {
        id: "N2",
        date: "2024-04-02",
        author: "Inspector Johnson",
        content:
          "Interviewed neighbors. One witness reports seeing suspicious vehicle.",
      },
      {
        id: "N3",
        date: "2024-04-03",
        author: "Forensics Team",
        content:
          "Fingerprint analysis in progress. Preliminary matches found in database.",
      },
    ],
  },
  {
    id: "CM-2024-002",
    crimeReportId: "CR-2024-002",
    title: "Vehicle Theft Investigation",
    status: "Active",
    priority: "Medium",
    dateOpened: "2024-04-02",
    description: "Investigation into stolen Honda Civic from mall parking lot.",
    assignedTo: "Sergeant Adams",
    lastUpdated: "2024-04-05",
    progress: 40,
    notes: [
      {
        id: "N1",
        date: "2024-04-02",
        author: "Officer Wilson",
        content:
          "Vehicle details entered into stolen vehicle database. APB issued.",
      },
      {
        id: "N2",
        date: "2024-04-03",
        author: "Sergeant Adams",
        content:
          "Reviewing mall security footage. Potential suspect identified.",
      },
      {
        id: "N3",
        date: "2024-04-05",
        author: "Detective Brooks",
        content:
          "Similar theft pattern identified in neighboring district. Coordinating with their team.",
      },
    ],
  },
  {
    id: "CM-2024-003",
    crimeReportId: "CR-2024-003",
    title: "Nightclub Assault Investigation",
    status: "Active",
    priority: "High",
    dateOpened: "2024-04-03",
    description: "Investigation into physical assault at downtown nightclub.",
    assignedTo: "Inspector Johnson",
    lastUpdated: "2024-04-06",
    progress: 35,
    notes: [
      {
        id: "N1",
        date: "2024-04-03",
        author: "Officer Johnson",
        content:
          "Victim statement taken at hospital. Moderate injuries sustained.",
      },
      {
        id: "N2",
        date: "2024-04-04",
        author: "Inspector Johnson",
        content:
          "Nightclub security footage obtained. Clear visual of the altercation.",
      },
      {
        id: "N3",
        date: "2024-04-06",
        author: "Detective Morris",
        content:
          "Suspect identified from footage. Criminal history includes previous assault charges.",
      },
    ],
  },
  {
    id: "CM-2024-004",
    crimeReportId: "CR-2024-004",
    title: "Shoplifting Case",
    status: "Closed",
    priority: "Low",
    dateOpened: "2024-04-03",
    description: "Case involving shoplifting at Main Street Mall.",
    assignedTo: "Officer Smith",
    lastUpdated: "2024-04-04",
    progress: 100,
    notes: [
      {
        id: "N1",
        date: "2024-04-03",
        author: "Officer Clark",
        content: "Suspect apprehended at the scene with stolen merchandise.",
      },
      {
        id: "N2",
        date: "2024-04-04",
        author: "Officer Smith",
        content: "Suspect processed and charged. Case closed with guilty plea.",
      },
    ],
  },
  {
    id: "CM-2024-006",
    crimeReportId: "CR-2024-006",
    title: "Bank Robbery Investigation",
    status: "Active",
    priority: "Critical",
    dateOpened: "2024-04-05",
    description: "Investigation into armed robbery at First National Bank.",
    assignedTo: "Detective Thompson",
    lastUpdated: "2024-04-10",
    progress: 65,
    notes: [
      {
        id: "N1",
        date: "2024-04-05",
        author: "Officer Rodriguez",
        content:
          "Multiple witness statements collected. Clear description of suspects.",
      },
      {
        id: "N2",
        date: "2024-04-06",
        author: "Forensics Team",
        content:
          "Fingerprints recovered from counter and door. Processing in progress.",
      },
      {
        id: "N3",
        date: "2024-04-08",
        author: "Detective Thompson",
        content:
          "Suspects identified as repeat offenders. Coordinating with FBI.",
      },
      {
        id: "N4",
        date: "2024-04-10",
        author: "SWAT Team",
        content:
          "Raid conducted on suspect location. One suspect apprehended, one at large.",
      },
    ],
  },
];

export const users = [
  {
    id: "1",
    name: "Admin User",
    email: "admin@crms.com",
    role: "admin",
    department: "IT & Administration",
    status: "active",
    lastLogin: "2024-04-21 09:15",
  },
  {
    id: "2",
    name: "Officer Smith",
    email: "officer@crms.com",
    role: "officer",
    department: "Patrol Division",
    status: "active",
    lastLogin: "2024-04-21 08:30",
  },
  {
    id: "3",
    name: "Inspector Johnson",
    email: "investigator@crms.com",
    role: "investigator",
    department: "Criminal Investigation Division",
    status: "active",
    lastLogin: "2024-04-21 10:45",
  },
  {
    id: "4",
    name: "Officer Wilson",
    email: "wilson@crms.com",
    role: "officer",
    department: "Patrol Division",
    status: "active",
    lastLogin: "2024-04-20 23:15",
  },
  {
    id: "5",
    name: "Sergeant Adams",
    email: "adams@crms.com",
    role: "investigator",
    department: "Criminal Investigation Division",
    status: "active",
    lastLogin: "2024-04-21 07:30",
  },
  {
    id: "6",
    name: "Captain Reynolds",
    email: "reynolds@crms.com",
    role: "admin",
    department: "Administration",
    status: "active",
    lastLogin: "2024-04-19 14:20",
  },
  {
    id: "7",
    name: "Officer Martinez",
    email: "martinez@crms.com",
    role: "officer",
    department: "Traffic Division",
    status: "inactive",
    lastLogin: "2024-04-15 11:10",
  },
  {
    id: "8",
    name: "Detective Thompson",
    email: "thompson@crms.com",
    role: "investigator",
    department: "Special Crimes Unit",
    status: "active",
    lastLogin: "2024-04-21 06:45",
  },
];

export const evidenceFiles = [
  {
    id: "EV-2024-001",
    caseId: "CM-2024-001",
    fileName: "fingerprints.jpg",
    fileType: "image/jpeg",
    fileSize: "2.4MB",
    description: "Fingerprints collected from rear window entry point",
    uploadedBy: "Officer Smith",
    uploadDate: "2024-04-01",
    tags: ["fingerprints", "entry point"],
    securityLevel: "Restricted",
  },
  {
    id: "EV-2024-002",
    caseId: "CM-2024-001",
    fileName: "security_footage.mp4",
    fileType: "video/mp4",
    fileSize: "156MB",
    description: "Neighborhood security camera footage showing suspect",
    uploadedBy: "Officer Smith",
    uploadDate: "2024-04-01",
    tags: ["video", "suspect", "security camera"],
    securityLevel: "Confidential",
  },
  {
    id: "EV-2024-003",
    caseId: "CM-2024-002",
    fileName: "mall_parking_footage.mp4",
    fileType: "video/mp4",
    fileSize: "230MB",
    description: "Mall parking lot security footage showing vehicle theft",
    uploadedBy: "Officer Wilson",
    uploadDate: "2024-04-02",
    tags: ["video", "vehicle theft", "security camera"],
    securityLevel: "Restricted",
  },
  {
    id: "EV-2024-004",
    caseId: "CM-2024-003",
    fileName: "victim_statement.pdf",
    fileType: "application/pdf",
    fileSize: "1.2MB",
    description: "Written statement from assault victim",
    uploadedBy: "Officer Johnson",
    uploadDate: "2024-04-03",
    tags: ["statement", "victim", "document"],
    securityLevel: "Confidential",
  },
  {
    id: "EV-2024-005",
    caseId: "CM-2024-003",
    fileName: "nightclub_footage.mp4",
    fileType: "video/mp4",
    fileSize: "345MB",
    description: "Nightclub security footage showing assault incident",
    uploadedBy: "Inspector Johnson",
    uploadDate: "2024-04-04",
    tags: ["video", "assault", "security camera"],
    securityLevel: "Restricted",
  },
  {
    id: "EV-2024-006",
    caseId: "CM-2024-006",
    fileName: "bank_camera_1.mp4",
    fileType: "video/mp4",
    fileSize: "178MB",
    description: "Bank interior camera footage of robbery",
    uploadedBy: "Officer Rodriguez",
    uploadDate: "2024-04-05",
    tags: ["video", "robbery", "security camera"],
    securityLevel: "Confidential",
  },
  {
    id: "EV-2024-007",
    caseId: "CM-2024-006",
    fileName: "weapon_photos.zip",
    fileType: "application/zip",
    fileSize: "15.7MB",
    description: "Photographs of weapon recovered at scene",
    uploadedBy: "Detective Thompson",
    uploadDate: "2024-04-08",
    tags: ["photos", "weapon", "evidence"],
    securityLevel: "Highly Restricted",
  },
  {
    id: "EV-2024-008",
    caseId: "CM-2024-006",
    fileName: "witness_statements.pdf",
    fileType: "application/pdf",
    fileSize: "3.5MB",
    description: "Compiled witness statements from bank customers and staff",
    uploadedBy: "Officer Rodriguez",
    uploadDate: "2024-04-05",
    tags: ["statements", "witnesses", "document"],
    securityLevel: "Restricted",
  },
];

export const crimeStatistics = {
  monthlyCrimes: [
    { month: "Jan", count: 42 },
    { month: "Feb", count: 38 },
    { month: "Mar", count: 45 },
    { month: "Apr", count: 40 },
    { month: "May", count: 33 },
    { month: "Jun", count: 37 },
    { month: "Jul", count: 45 },
    { month: "Aug", count: 52 },
    { month: "Sep", count: 48 },
    { month: "Oct", count: 41 },
    { month: "Nov", count: 38 },
    { month: "Dec", count: 35 },
  ],
  crimeTypes: [
    { type: "Theft", count: 120 },
    { type: "Assault", count: 85 },
    { type: "Burglary", count: 65 },
    { type: "Vandalism", count: 45 },
    { type: "Fraud", count: 40 },
    { type: "Robbery", count: 25 },
    { type: "Other", count: 50 },
  ],
  caseStatus: [
    { status: "Open", count: 145 },
    { status: "In Progress", count: 87 },
    { status: "Closed", count: 210 },
  ],
  districtData: [
    { district: "Downtown", count: 85 },
    { district: "North Side", count: 65 },
    { district: "West End", count: 45 },
    { district: "East Side", count: 72 },
    { district: "South District", count: 58 },
    { district: "Central", count: 90 },
  ],
  timeOfDay: [
    { time: "00:00-04:00", count: 62 },
    { time: "04:00-08:00", count: 35 },
    { time: "08:00-12:00", count: 48 },
    { time: "12:00-16:00", count: 78 },
    { time: "16:00-20:00", count: 95 },
    { time: "20:00-24:00", count: 112 },
  ],
  solvedRate: {
    solved: 65,
    unsolved: 35,
  },
  yearComparison: {
    current: 430,
    previous: 395,
    change: 8.9,
  },
};
